services:
  web1:
    image: nginx:alpine
    container_name: web1
    restart: unless-stopped
    volumes:
      - ./web/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./htdocs/:/usr/share/nginx/html
    expose:
      - 80

  web2:
    container_name: web2
    extends:
      service: web1

  haproxy:
    image: haproxy:2.3
    container_name: haproxy
    volumes:
      - ./web/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - web1
      - web2
    ports:
      - "8080:80"